### ISSUE TITLE
Contributions wanted?

### ISSUE THREAD

**Issue by fire** [CaptainProton42/GodotHoloPlayExtension#2]
What is missing?

**Comment by CaptainProton42** [comment]
Basically everything, I haven't started implementing anything yet. The extension currently just registers a HoloPlay Service app and adds node that inherits `Node3D` to the editor.

My general plan is to do a pretty direct conversion of the code from the 3.x plugin but replace all native/OpenGL/GLFW code with Godot built-ins (such as `RenderingDevice` and possibly `DisplayServer`).  The editor plugin from https://github.com/CaptainProton42/GodotHoloPlay should also be rewritten in C++ so everything is in one place in this repo.

I'm a bit busy currently but I'll try to make a structured list with things that need to be done here as soon as I have some more time.

I'm thankful for any contribution, be it ideas or even code.

Edit: Had some time now and created a [rough draft](https://github.com/CaptainProton42/GodotHoloPlayExtension/issues/3).

**Comment by CaptainProton42** [comment]
I think the roadmap #3 is relatively detailed now, closing this.
